/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BleedAdjustment: typeof import('./src/components/steps/BleedAdjustment.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    FilePicker: typeof import('./src/components/FilePicker.vue')['default']
    FileUploader: typeof import('./src/components/FileUploader.vue')['default']
    HighlightedText: typeof import('./src/components/HighlightedText.vue')['default']
    IconBleedy: typeof import('./src/components/icons/IconBleedy.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    ImageGallery: typeof import('./src/components/ImageGallery.vue')['default']
    ImageGalleryBase: typeof import('./src/components/ImageGalleryBase.vue')['default']
    ImageGalleryItem: typeof import('./src/components/ImageGalleryItem.vue')['default']
    ImageProcessingProgress: typeof import('./src/components/ImageProcessingProgress.vue')['default']
    ImageProcessor: typeof import('./src/components/ImageProcessor.vue')['default']
    ImageSelection: typeof import('./src/components/ImageSelection.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    ProcessImages: typeof import('./src/components/steps/ProcessImages.vue')['default']
    ReviewResults: typeof import('./src/components/steps/ReviewResults.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchToolbar: typeof import('./src/components/SearchToolbar.vue')['default']
    SelectionTools: typeof import('./src/components/SelectionTools.vue')['default']
    SketchyCheckmark: typeof import('./src/components/icons/SketchyCheckmark.vue')['default']
    StepManager: typeof import('./src/components/StepManager.vue')['default']
  }
}
