/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BleedAdjustment: typeof import('./src/components/BleedAdjustment.vue')['default']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    FilePicker: typeof import('./src/components/FilePicker.vue')['default']
    FileUploader: typeof import('./src/components/FileUploader.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconBleedy: typeof import('./src/components/icons/IconBleedy.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    ImageGallery: typeof import('./src/components/ImageGallery.vue')['default']
    ImageProcessor: typeof import('./src/components/ImageProcessor.vue')['default']
    ImageSelection: typeof import('./src/components/ImageSelection.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    ProcessImages: typeof import('./src/components/ProcessImages.vue')['default']
    ReviewResults: typeof import('./src/components/ReviewResults.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectionTools: typeof import('./src/components/SelectionTools.vue')['default']
    StepManager: typeof import('./src/components/StepManager.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
